### ISSUE TITLE
Trello - Nice to have

### ISSUE THREAD

**Issue by Djidiouf** [ThomasGirard/java-bot#4]
+trello create patitans
>> Card [patitans 36] has been created (without description)
>> https://trello.com/ggmm/okfpy

+trello amend patitans 36 = --2v2-- Encore plus de PA pour le peuple !\n\nCar il n'y a que les vidéos sur ce jeu là que vous regardez, en voilà encore !
>> Card [patitans 36] has been amended (with description)
>> https://trello.com/ggmm/okfpy

+trello amend patitans 36 = --2v2AI-- Il y a alerte les amis !\n\nPA, encore plus de PA !
>> Card [patitans 36] already had a description
>> = --2v2-- Encore plus de PA pour le peuple !
>>
>> Car il n'y a que les vidéos sur ce jeu là que vous regardez, en voilà encore !
>> EOT
>> Card [patitans 36] has been amended (with description)

>> https://trello.com/ggmm/okfpy

+trello create vagante = Le barrage à zombie\n\nLes zombies sont devenus fous et s'en prennent directement aux mains géantes !
>> Card [vagante 06] has been created (with description)
>> https://trello.com/ggmm/tfgiu

+trello create conanexiles 03 = Les bijoux de famille\n\nQuand y'en a trop, il faut les enterrer, mais où?
>> Card [conanexiles 03] has been created (with description)
>> https://trello.com/ggmm/plmid

**Comment by ThomasGirard** [comment]
Will be implemented on next release.

On card creation, all these will be valid (description takes \n as a line break)
+trello create <gamename>
+trello create <gamename> <number>
+trello create <gamename> <description>
+trello create <gamename> <number> <description>

+trello describe will have inline and interactive mode : 
E.g. inline mode : 
+trello describe <gamename> <number> This is \n\na description
Interactive mode : 
+trello describe <gamename> <number>
> Please enter title and description etc. etc. followed by +trello commit

**Comment by ThomasGirard** [comment]
Fixed by commit 06dc2cb11fdba88cc96f10cc655a88ff9a6d567c
